import type {
  Patient,
  Professional,
  Room,
  AppointmentType,
  Appointment,
  MedicalNote,
  AuditLog,
  NotificationItem,
  DashboardOverview,
  UserProfile,
} from "@/types/infinity";

export const DEMO_PROFILES: UserProfile[] = [
  {
    id: "user-demo-admin",
    fullName: "Administrador Infinity",
    email: "admin@grupoinfinity.med.br",
    role: "ADMINISTRADOR",
    isActive: true,
    createdAt: "2026-01-01T08:00:00Z",
  },
  {
    id: "user-demo-dra-rhauana",
    fullName: "Dra. Rhauana Ângela",
    email: "dra.rhauana@grupoinfinity.med.br",
    role: "MEDICO",
    isActive: true,
    createdAt: "2026-01-01T08:00:00Z",
  },
  {
    id: "user-demo-recepcao",
    fullName: "Recepção Infinity",
    email: "recepcao@grupoinfinity.med.br",
    role: "RECEPCAO",
    isActive: true,
    createdAt: "2026-01-01T08:00:00Z",
  },
  {
    id: "user-demo-enfermagem",
    fullName: "Enf. Patrícia Gomes",
    email: "enfermagem@grupoinfinity.med.br",
    role: "ENFERMAGEM",
    isActive: true,
    createdAt: "2026-01-01T08:00:00Z",
  },
];

export const DEMO_PROFESSIONALS: Professional[] = [
  {
    id: "prof-01",
    fullName: "Dra. Rhauana Ângela",
    councilType: "CRM",
    councilNumber: "35139",
    councilState: "GO",
    phone: "(62) 99876-5432",
    email: "dra.rhauana@grupoinfinity.med.br",
    colorHex: "#c5a880",
    isActive: true,
    specialties: ["Medicina Estética", "Medicina Regenerativa", "Técnica 4K"],
  },
  {
    id: "prof-02",
    fullName: "Dr. André Silveira",
    councilType: "CRM",
    councilNumber: "28410",
    councilState: "GO",
    phone: "(62) 99123-4567",
    email: "dr.andre@grupoinfinity.med.br",
    colorHex: "#4a5568",
    isActive: true,
    specialties: ["Cirurgia Plástica", "Contorno Corporal Avançado"],
  },
  {
    id: "prof-03",
    fullName: "Ft. Camila Vasconcelos",
    councilType: "CREFITO",
    councilNumber: "44321",
    councilState: "GO",
    phone: "(62) 99345-6789",
    email: "camila.fisio@grupoinfinity.med.br",
    colorHex: "#805ad5",
    isActive: true,
    specialties: ["Fisioterapia Dermato-Funcional", "Pós-Operatório"],
  },
  {
    id: "prof-04",
    fullName: "Enf. Patrícia Gomes",
    councilType: "COREN",
    councilNumber: "129400",
    councilState: "GO",
    phone: "(62) 99456-7890",
    email: "patricia.enf@grupoinfinity.med.br",
    colorHex: "#2b6cb0",
    isActive: true,
    specialties: ["Enfermagem Cirúrgica", "CME & Biossegurança"],
  },
];

export const DEMO_ROOMS: Room[] = [
  { id: "room-01", name: "Consultório 01 — Dra. Rhauana", type: "CONSULTORIO", isActive: true },
  {
    id: "room-02",
    name: "Consultório 02 — Avaliação Integrada",
    type: "CONSULTORIO",
    isActive: true,
  },
  { id: "room-03", name: "Sala de Procedimentos 4K — 01", type: "PROCEDIMENTOS", isActive: true },
  {
    id: "room-04",
    name: "Centro Cirúrgico Infinity — Sala A",
    type: "CENTRO_CIRURGICO",
    isActive: true,
  },
  { id: "room-05", name: "Sala de Recuperação — Leito 01", type: "RECUPERACAO", isActive: true },
];

export const DEMO_APPOINTMENT_TYPES: AppointmentType[] = [
  {
    id: "type-01",
    name: "Avaliação Inicial Técnica 4K",
    durationMinutes: 45,
    colorHex: "#c5a880",
    isActive: true,
  },
  {
    id: "type-02",
    name: "Consulta Médica de Acompanhamento",
    durationMinutes: 30,
    colorHex: "#536878",
    isActive: true,
  },
  {
    id: "type-03",
    name: "Procedimento Contorno 4K",
    durationMinutes: 150,
    colorHex: "#2d5a27",
    isActive: true,
  },
  {
    id: "type-04",
    name: "Retorno Pós-Procedimento",
    durationMinutes: 20,
    colorHex: "#4a5568",
    isActive: true,
  },
  {
    id: "type-05",
    name: "Sessão Pós-Operatória Fisioterapia",
    durationMinutes: 40,
    colorHex: "#805ad5",
    isActive: true,
  },
];

export const DEMO_PATIENTS: Patient[] = [
  {
    id: "patient-demo-001",
    fullName: "Mariana Costa Silveira",
    cpf: "74125896300",
    birthDate: "1989-05-14",
    gender: "F",
    phone: "(62) 98111-2233",
    email: "mariana.costa@exemplo.com",
    status: "IN_TREATMENT",
    emergencyContactName: "Rodrigo Silveira (Esposo)",
    emergencyContactPhone: "(62) 98111-9988",
    clinicalSummary:
      "Paciente em planejamento para abordagem de gordura localizada em flancos e abdômen inferior pela Técnica 4K. Nega alergias medicamentosas.",
    createdAt: "2026-08-20T10:00:00Z",
    updatedAt: "2026-09-08T14:30:00Z",
    documentsCount: 4,
    lastAppointmentDate: "2026-09-09T09:00:00Z",
    address: {
      street: "Avenida 136",
      number: "761",
      complement: "Apto 1402",
      neighborhood: "Setor Sul",
      city: "Goiânia",
      state: "GO",
      zipCode: "74093-250",
    },
  },
  {
    id: "patient-demo-002",
    fullName: "Rafael Mendonça Dias",
    cpf: "85236914722",
    birthDate: "1982-11-28",
    gender: "M",
    phone: "(62) 98222-3344",
    email: "rafael.dias@exemplo.com",
    status: "POST_PROCEDURE",
    emergencyContactName: "Cláudia Mendonça (Irmã)",
    emergencyContactPhone: "(62) 98222-8877",
    clinicalSummary:
      "Pós-procedimento imediato de contorno abdominal realizado em 01/09/2026. Em drenagem e acompanhamento pós-operatório.",
    createdAt: "2026-08-10T11:20:00Z",
    updatedAt: "2026-09-08T16:00:00Z",
    documentsCount: 6,
    lastAppointmentDate: "2026-09-09T10:30:00Z",
    address: {
      street: "Rua T-53",
      number: "180",
      neighborhood: "Setor Bueno",
      city: "Goiânia",
      state: "GO",
      zipCode: "74215-110",
    },
  },
  {
    id: "patient-demo-003",
    fullName: "Juliana Alencar Prado",
    cpf: "96314725833",
    birthDate: "1995-03-08",
    gender: "F",
    phone: "(62) 98333-4455",
    email: "juliana.prado@exemplo.com",
    status: "ACTIVE",
    emergencyContactName: "Marcos Prado (Pai)",
    emergencyContactPhone: "(62) 98333-7766",
    clinicalSummary:
      "Avaliação clínica inicial realizada. Solicitados exames pré-operatórios de coagulograma e ultrassom de parede abdominal.",
    createdAt: "2026-09-02T14:15:00Z",
    updatedAt: "2026-09-07T11:00:00Z",
    documentsCount: 2,
    lastAppointmentDate: "2026-09-09T14:00:00Z",
    address: {
      street: "Alameda Ricardo Paranhos",
      number: "340",
      neighborhood: "Setor Marista",
      city: "Goiânia",
      state: "GO",
      zipCode: "74180-050",
    },
  },
  {
    id: "patient-demo-004",
    fullName: "Beatriz Nogueira Lima",
    cpf: "15935748644",
    birthDate: "1991-07-22",
    gender: "F",
    phone: "(62) 98444-5566",
    email: "beatriz.nogueira@exemplo.com",
    status: "ACTIVE",
    clinicalSummary: "Interesse em protocolo regenerativo facial e avaliação de contorno corporal.",
    createdAt: "2026-09-05T09:40:00Z",
    updatedAt: "2026-09-05T09:40:00Z",
    documentsCount: 1,
    lastAppointmentDate: "2026-09-09T15:30:00Z",
  },
  {
    id: "patient-demo-005",
    fullName: "Carlos Eduardo Ramos",
    cpf: "35795124655",
    birthDate: "1978-09-30",
    gender: "M",
    phone: "(62) 98555-6677",
    email: "carlos.ramos@exemplo.com",
    status: "INACTIVE",
    clinicalSummary: "Tratamento de contorno corporal concluído com alta médica em maio/2026.",
    createdAt: "2026-04-12T08:00:00Z",
    updatedAt: "2026-05-20T17:00:00Z",
    documentsCount: 5,
  },
];

export const DEMO_APPOINTMENTS: Appointment[] = [
  {
    id: "app-01",
    patientId: "patient-demo-001",
    patientName: "Mariana Costa Silveira",
    patientPhone: "(62) 98111-2233",
    professionalId: "prof-01",
    professionalName: "Dra. Rhauana Ângela",
    roomId: "room-01",
    roomName: "Consultório 01 — Dra. Rhauana",
    appointmentTypeId: "type-01",
    appointmentTypeName: "Avaliação Inicial Técnica 4K",
    startTime: "2026-09-09T09:00:00-03:00",
    endTime: "2026-09-09T09:45:00-03:00",
    status: "IN_PROGRESS",
    notes: "Definição de planejamento anatômico para região de flancos.",
    createdAt: "2026-09-05T11:00:00Z",
  },
  {
    id: "app-02",
    patientId: "patient-demo-002",
    patientName: "Rafael Mendonça Dias",
    patientPhone: "(62) 98222-3344",
    professionalId: "prof-03",
    professionalName: "Ft. Camila Vasconcelos",
    roomId: "room-05",
    roomName: "Recuperação — Leito 01",
    appointmentTypeId: "type-05",
    appointmentTypeName: "Sessão Pós-Operatória Fisioterapia",
    startTime: "2026-09-09T10:30:00-03:00",
    endTime: "2026-09-09T11:10:00-03:00",
    status: "CONFIRMED",
    notes: "Drenagem linfática manual pós-procedimento D8.",
    createdAt: "2026-09-06T14:30:00Z",
  },
  {
    id: "app-03",
    patientId: "patient-demo-003",
    patientName: "Juliana Alencar Prado",
    patientPhone: "(62) 98333-4455",
    professionalId: "prof-01",
    professionalName: "Dra. Rhauana Ângela",
    roomId: "room-01",
    roomName: "Consultório 01 — Dra. Rhauana",
    appointmentTypeId: "type-02",
    appointmentTypeName: "Consulta Médica de Acompanhamento",
    startTime: "2026-09-09T14:00:00-03:00",
    endTime: "2026-09-09T14:30:00-03:00",
    status: "CONFIRMED",
    notes: "Checagem de resultados de exames de imagem.",
    createdAt: "2026-09-07T09:15:00Z",
  },
  {
    id: "app-04",
    patientId: "patient-demo-004",
    patientName: "Beatriz Nogueira Lima",
    patientPhone: "(62) 98444-5566",
    professionalId: "prof-02",
    professionalName: "Dr. André Silveira",
    roomId: "room-02",
    roomName: "Consultório 02 — Avaliação Integrada",
    appointmentTypeId: "type-01",
    appointmentTypeName: "Avaliação Inicial Técnica 4K",
    startTime: "2026-09-09T15:30:00-03:00",
    endTime: "2026-09-09T16:15:00-03:00",
    status: "SCHEDULED",
    notes: "Primeira consulta agendada pelo WhatsApp institucional.",
    createdAt: "2026-09-08T10:00:00Z",
  },
];

export const DEMO_MEDICAL_NOTES: MedicalNote[] = [
  {
    id: "note-01",
    medicalRecordId: "rec-001",
    patientId: "patient-demo-001",
    professionalId: "prof-01",
    professionalName: "Dra. Rhauana Ângela",
    professionalCouncil: "CRM/GO 35139",
    noteDate: "2026-09-09T09:15:00-03:00",
    noteType: "CONSULTA",
    title: "Avaliação Médica de Planejamento — Técnica 4K",
    content:
      "Paciente comparece para planejamento cirúrgico ambulatorial. Exame físico evidencia tecido adiposo localizado em flancos bilaterais e abdômen infraumbilical com boa elasticidade cutânea, sem presença de hérnias ou diástases clinicamente relevantes. Exames laboratoriais de rotina revisados sem alterações dignas de nota. Discutidos os objetivos, limitações éticas do procedimento e orientações do pós-operatório.",
    vitalSigns: {
      bloodPressure: "120/80 mmHg",
      heartRate: 72,
      weight: 64.2,
      height: 168,
      temperature: 36.4,
    },
    conduct:
      "1. Indicado protocolo da Técnica 4K para flancos bilaterais.\n2. Prescrito preparo prévio e profilaxias habituais.\n3. Termo de consentimento esclarecido entregue e explicado à paciente.\n4. Procedimento programado para 18/09/2026 no Centro Cirúrgico Infinity.",
    createdBy: "Dra. Rhauana Ângela",
    createdAt: "2026-09-09T09:40:00Z",
  },
  {
    id: "note-02",
    medicalRecordId: "rec-001",
    patientId: "patient-demo-001",
    professionalId: "prof-01",
    professionalName: "Dra. Rhauana Ângela",
    professionalCouncil: "CRM/GO 35139",
    noteDate: "2026-09-01T11:00:00-03:00",
    noteType: "AVALIACAO",
    title: "Primeiro Atendimento e Anamnese Clínica",
    content:
      "Paciente relata queixa de gordura localizada refratária a exercícios físicos e dieta há aproximadamente 3 anos. Nega comorbidades crônicas, hipertensão, diabetes ou tabagismo. Alergias: nega. Nega cirurgias prévias no abdômen.",
    vitalSigns: {
      bloodPressure: "118/76 mmHg",
      heartRate: 68,
      weight: 64.8,
      height: 168,
    },
    conduct:
      "Solicitado hemograma completo, coagulograma, glicemia de jejum, função renal e ultrassonografia de parede abdominal.",
    createdBy: "Dra. Rhauana Ângela",
    createdAt: "2026-09-01T11:30:00Z",
  },
  {
    id: "note-03",
    medicalRecordId: "rec-001",
    patientId: "patient-demo-001",
    professionalId: "prof-04",
    professionalName: "Enf. Patrícia Gomes",
    professionalCouncil: "COREN/GO 129400",
    noteDate: "2026-08-25T14:00:00-03:00",
    noteType: "PRIMEIRO_ATENDIMENTO",
    title: "Triagem Assistencial e Acolhimento",
    content:
      "Realizada aferição de sinais vitais, conferência de cadastro e orientações gerais sobre as etapas do atendimento clínico.",
    vitalSigns: {
      bloodPressure: "120/80 mmHg",
      heartRate: 70,
    },
    conduct: "Encaminhada ao consultório médico.",
    createdBy: "Enf. Patrícia Gomes",
    createdAt: "2026-08-25T14:15:00Z",
  },
];

export const DEMO_AUDIT_LOGS: AuditLog[] = [
  {
    id: "audit-01",
    userId: "user-demo-dra-rhauana",
    userName: "Dra. Rhauana Ângela",
    action: "CREATE",
    entityType: "medical_notes",
    entityId: "note-01",
    description: "Evolução clínica registrada no prontuário de Mariana Costa Silveira",
    ipAddress: "187.56.24.110",
    userAgent: "InfinityOS / Chrome 128 (Windows NT 10.0)",
    createdAt: "2026-09-09T09:40:12Z",
  },
  {
    id: "audit-02",
    userId: "user-demo-dra-rhauana",
    userName: "Dra. Rhauana Ângela",
    action: "VIEW_SENSITIVE_DATA",
    entityType: "medical_records",
    entityId: "rec-001",
    description:
      "Visualização de dados sensíveis e histórico clínico do paciente Mariana Costa Silveira",
    ipAddress: "187.56.24.110",
    createdAt: "2026-09-09T09:12:04Z",
  },
  {
    id: "audit-03",
    userId: "user-demo-recepcao",
    userName: "Recepção Infinity",
    action: "UPDATE",
    entityType: "appointments",
    entityId: "app-01",
    description: 'Status da consulta alterado para "Em Atendimento"',
    ipAddress: "187.56.24.115",
    createdAt: "2026-09-09T09:05:30Z",
  },
  {
    id: "audit-04",
    userId: "user-demo-recepcao",
    userName: "Recepção Infinity",
    action: "CREATE",
    entityType: "appointments",
    entityId: "app-04",
    description: "Nova consulta agendada para Beatriz Nogueira Lima com Dr. André Silveira",
    ipAddress: "187.56.24.115",
    createdAt: "2026-09-08T10:00:22Z",
  },
  {
    id: "audit-05",
    userId: "user-demo-admin",
    userName: "Administrador Infinity",
    action: "LOGIN",
    entityType: "auth_session",
    description: "Autenticação bem-sucedida no Infinity OS",
    ipAddress: "187.56.24.101",
    createdAt: "2026-09-08T08:00:01Z",
  },
];

export const DEMO_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif-01",
    title: "Termo pendente de assinatura",
    message:
      "Mariana Costa Silveira ainda precisa assinar o termo digital para o procedimento de 18/09.",
    type: "WARNING",
    createdAt: "2026-09-09T08:30:00Z",
  },
  {
    id: "notif-02",
    title: "Exames laboratoriais recebidos",
    message: "Laudos de coagulograma e hemograma de Juliana Alencar Prado anexados ao prontuário.",
    type: "INFO",
    createdAt: "2026-09-09T07:45:00Z",
  },
  {
    id: "notif-03",
    title: "Retorno pós-procedimento confirmado",
    message:
      "Rafael Mendonça Dias confirmou presença para a sessão com Ft. Camila Vasconcelos hoje às 10:30.",
    type: "SUCCESS",
    createdAt: "2026-09-09T07:15:00Z",
  },
  {
    id: "notif-04",
    title: "Alerta de escala CME",
    message:
      "Ciclo de esterilização do kit de cânulas 4K concluído com sucesso e testes biológicos validados.",
    type: "INFO",
    createdAt: "2026-09-08T19:00:00Z",
  },
];

export const DEMO_DASHBOARD: DashboardOverview = {
  patientsTodayCount: 4,
  appointmentsTodayCount: 4,
  proceduresMonthCount: 18,
  surgeriesMonthCount: 6,
  pendingIssuesCount: 5,
  monthlyRevenueFormatted: "R$ 248.500,00",
  todayAppointments: DEMO_APPOINTMENTS,
  pendingItems: [
    {
      id: "pend-01",
      title: "Termo de Consentimento Esclarecido",
      description: "Aguardando assinatura digital de Mariana Costa Silveira.",
      category: "DOCUMENT",
      severity: "HIGH",
      date: "Hoje, 09/09",
    },
    {
      id: "pend-02",
      title: "Retorno clínico de 15 dias",
      description: "Rafael Mendonça Dias necessita agendar revisão fotográfica pós-procedimento.",
      category: "RETURN",
      severity: "MEDIUM",
      date: "Vence em 2 dias",
    },
    {
      id: "pend-03",
      title: "Exames de imagem pendentes",
      description:
        "Ultrassonografia de abdômen de Juliana Alencar Prado aguardando envio pelo laboratório.",
      category: "EXAME",
      severity: "MEDIUM",
      date: "10/09/2026",
    },
    {
      id: "pend-04",
      title: "Cirurgia agendada — Preparo de Sala",
      description: "Centro Cirúrgico Sala A: conferência de kits de cânulas esterilizados.",
      category: "PROCEDURE",
      severity: "HIGH",
      date: "Amanhã, 07:30",
    },
    {
      id: "pend-05",
      title: "Confirmação de faturamento convênio/particular",
      description: "2 orçamentos de Técnica 4K aguardando aprovação financeira da paciente.",
      category: "PAYMENT",
      severity: "LOW",
      date: "11/09/2026",
    },
  ],
  recentActivity: DEMO_AUDIT_LOGS,
};
