/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedGestaoCrmRouteImport } from './routes/_authenticated/gestao/crm'
import { Route as AuthenticatedGestaoDocumentosRouteImport } from './routes/_authenticated/gestao/documentos'
import { Route as AuthenticatedGestaoEquipeRouteImport } from './routes/_authenticated/gestao/equipe'
import { Route as AuthenticatedGestaoEstoqueRouteImport } from './routes/_authenticated/gestao/estoque'
import { Route as AuthenticatedGestaoFinanceiroRouteImport } from './routes/_authenticated/gestao/financeiro'
import { Route as AuthenticatedOperacaoCentroCirurgicoRouteImport } from './routes/_authenticated/operacao/centro-cirurgico'
import { Route as AuthenticatedOperacaoCmeRouteImport } from './routes/_authenticated/operacao/cme'
import { Route as AuthenticatedOperacaoConsultasRouteImport } from './routes/_authenticated/operacao/consultas'
import { Route as AuthenticatedOperacaoProcedimentosRouteImport } from './routes/_authenticated/operacao/procedimentos'
import { Route as AuthenticatedOperacaoProntuariosRouteImport } from './routes/_authenticated/operacao/prontuarios'
import { Route as AuthenticatedOperacaoRecuperacaoRouteImport } from './routes/_authenticated/operacao/recuperacao'
import { Route as AuthenticatedPacientesIndexRouteImport } from './routes/_authenticated/pacientes/index'
import { Route as AuthenticatedPacientesPacienteIdRouteImport } from './routes/_authenticated/pacientes/$pacienteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGestaoCrmRoute = AuthenticatedGestaoCrmRouteImport.update({
  id: '/gestao/crm',
  path: '/gestao/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGestaoDocumentosRoute =
  AuthenticatedGestaoDocumentosRouteImport.update({
    id: '/gestao/documentos',
    path: '/gestao/documentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGestaoEquipeRoute =
  AuthenticatedGestaoEquipeRouteImport.update({
    id: '/gestao/equipe',
    path: '/gestao/equipe',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGestaoEstoqueRoute =
  AuthenticatedGestaoEstoqueRouteImport.update({
    id: '/gestao/estoque',
    path: '/gestao/estoque',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGestaoFinanceiroRoute =
  AuthenticatedGestaoFinanceiroRouteImport.update({
    id: '/gestao/financeiro',
    path: '/gestao/financeiro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoCentroCirurgicoRoute =
  AuthenticatedOperacaoCentroCirurgicoRouteImport.update({
    id: '/operacao/centro-cirurgico',
    path: '/operacao/centro-cirurgico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoCmeRoute =
  AuthenticatedOperacaoCmeRouteImport.update({
    id: '/operacao/cme',
    path: '/operacao/cme',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoConsultasRoute =
  AuthenticatedOperacaoConsultasRouteImport.update({
    id: '/operacao/consultas',
    path: '/operacao/consultas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoProcedimentosRoute =
  AuthenticatedOperacaoProcedimentosRouteImport.update({
    id: '/operacao/procedimentos',
    path: '/operacao/procedimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoProntuariosRoute =
  AuthenticatedOperacaoProntuariosRouteImport.update({
    id: '/operacao/prontuarios',
    path: '/operacao/prontuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoRecuperacaoRoute =
  AuthenticatedOperacaoRecuperacaoRouteImport.update({
    id: '/operacao/recuperacao',
    path: '/operacao/recuperacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPacientesIndexRoute =
  AuthenticatedPacientesIndexRouteImport.update({
    id: '/pacientes/',
    path: '/pacientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPacientesPacienteIdRoute =
  AuthenticatedPacientesPacienteIdRouteImport.update({
    id: '/pacientes/$pacienteId',
    path: '/pacientes/$pacienteId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/gestao/crm': typeof AuthenticatedGestaoCrmRoute
  '/gestao/documentos': typeof AuthenticatedGestaoDocumentosRoute
  '/gestao/equipe': typeof AuthenticatedGestaoEquipeRoute
  '/gestao/estoque': typeof AuthenticatedGestaoEstoqueRoute
  '/gestao/financeiro': typeof AuthenticatedGestaoFinanceiroRoute
  '/operacao/centro-cirurgico': typeof AuthenticatedOperacaoCentroCirurgicoRoute
  '/operacao/cme': typeof AuthenticatedOperacaoCmeRoute
  '/operacao/consultas': typeof AuthenticatedOperacaoConsultasRoute
  '/operacao/procedimentos': typeof AuthenticatedOperacaoProcedimentosRoute
  '/operacao/prontuarios': typeof AuthenticatedOperacaoProntuariosRoute
  '/operacao/recuperacao': typeof AuthenticatedOperacaoRecuperacaoRoute
  '/pacientes/$pacienteId': typeof AuthenticatedPacientesPacienteIdRoute
  '/pacientes/': typeof AuthenticatedPacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/gestao/crm': typeof AuthenticatedGestaoCrmRoute
  '/gestao/documentos': typeof AuthenticatedGestaoDocumentosRoute
  '/gestao/equipe': typeof AuthenticatedGestaoEquipeRoute
  '/gestao/estoque': typeof AuthenticatedGestaoEstoqueRoute
  '/gestao/financeiro': typeof AuthenticatedGestaoFinanceiroRoute
  '/operacao/centro-cirurgico': typeof AuthenticatedOperacaoCentroCirurgicoRoute
  '/operacao/cme': typeof AuthenticatedOperacaoCmeRoute
  '/operacao/consultas': typeof AuthenticatedOperacaoConsultasRoute
  '/operacao/procedimentos': typeof AuthenticatedOperacaoProcedimentosRoute
  '/operacao/prontuarios': typeof AuthenticatedOperacaoProntuariosRoute
  '/operacao/recuperacao': typeof AuthenticatedOperacaoRecuperacaoRoute
  '/pacientes/$pacienteId': typeof AuthenticatedPacientesPacienteIdRoute
  '/pacientes': typeof AuthenticatedPacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/gestao/crm': typeof AuthenticatedGestaoCrmRoute
  '/_authenticated/gestao/documentos': typeof AuthenticatedGestaoDocumentosRoute
  '/_authenticated/gestao/equipe': typeof AuthenticatedGestaoEquipeRoute
  '/_authenticated/gestao/estoque': typeof AuthenticatedGestaoEstoqueRoute
  '/_authenticated/gestao/financeiro': typeof AuthenticatedGestaoFinanceiroRoute
  '/_authenticated/operacao/centro-cirurgico': typeof AuthenticatedOperacaoCentroCirurgicoRoute
  '/_authenticated/operacao/cme': typeof AuthenticatedOperacaoCmeRoute
  '/_authenticated/operacao/consultas': typeof AuthenticatedOperacaoConsultasRoute
  '/_authenticated/operacao/procedimentos': typeof AuthenticatedOperacaoProcedimentosRoute
  '/_authenticated/operacao/prontuarios': typeof AuthenticatedOperacaoProntuariosRoute
  '/_authenticated/operacao/recuperacao': typeof AuthenticatedOperacaoRecuperacaoRoute
  '/_authenticated/pacientes/$pacienteId': typeof AuthenticatedPacientesPacienteIdRoute
  '/_authenticated/pacientes/': typeof AuthenticatedPacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/agenda'
    | '/configuracoes'
    | '/dashboard'
    | '/painel'
    | '/relatorios'
    | '/gestao/crm'
    | '/gestao/documentos'
    | '/gestao/equipe'
    | '/gestao/estoque'
    | '/gestao/financeiro'
    | '/operacao/centro-cirurgico'
    | '/operacao/cme'
    | '/operacao/consultas'
    | '/operacao/procedimentos'
    | '/operacao/prontuarios'
    | '/operacao/recuperacao'
    | '/pacientes/$pacienteId'
    | '/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/agenda'
    | '/configuracoes'
    | '/dashboard'
    | '/painel'
    | '/relatorios'
    | '/gestao/crm'
    | '/gestao/documentos'
    | '/gestao/equipe'
    | '/gestao/estoque'
    | '/gestao/financeiro'
    | '/operacao/centro-cirurgico'
    | '/operacao/cme'
    | '/operacao/consultas'
    | '/operacao/procedimentos'
    | '/operacao/prontuarios'
    | '/operacao/recuperacao'
    | '/pacientes/$pacienteId'
    | '/pacientes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/login'
    | '/_authenticated/agenda'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/painel'
    | '/_authenticated/relatorios'
    | '/_authenticated/gestao/crm'
    | '/_authenticated/gestao/documentos'
    | '/_authenticated/gestao/equipe'
    | '/_authenticated/gestao/estoque'
    | '/_authenticated/gestao/financeiro'
    | '/_authenticated/operacao/centro-cirurgico'
    | '/_authenticated/operacao/cme'
    | '/_authenticated/operacao/consultas'
    | '/_authenticated/operacao/procedimentos'
    | '/_authenticated/operacao/prontuarios'
    | '/_authenticated/operacao/recuperacao'
    | '/_authenticated/pacientes/$pacienteId'
    | '/_authenticated/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestao/crm': {
      id: '/_authenticated/gestao/crm'
      path: '/gestao/crm'
      fullPath: '/gestao/crm'
      preLoaderRoute: typeof AuthenticatedGestaoCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestao/documentos': {
      id: '/_authenticated/gestao/documentos'
      path: '/gestao/documentos'
      fullPath: '/gestao/documentos'
      preLoaderRoute: typeof AuthenticatedGestaoDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestao/equipe': {
      id: '/_authenticated/gestao/equipe'
      path: '/gestao/equipe'
      fullPath: '/gestao/equipe'
      preLoaderRoute: typeof AuthenticatedGestaoEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestao/estoque': {
      id: '/_authenticated/gestao/estoque'
      path: '/gestao/estoque'
      fullPath: '/gestao/estoque'
      preLoaderRoute: typeof AuthenticatedGestaoEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestao/financeiro': {
      id: '/_authenticated/gestao/financeiro'
      path: '/gestao/financeiro'
      fullPath: '/gestao/financeiro'
      preLoaderRoute: typeof AuthenticatedGestaoFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/centro-cirurgico': {
      id: '/_authenticated/operacao/centro-cirurgico'
      path: '/operacao/centro-cirurgico'
      fullPath: '/operacao/centro-cirurgico'
      preLoaderRoute: typeof AuthenticatedOperacaoCentroCirurgicoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/cme': {
      id: '/_authenticated/operacao/cme'
      path: '/operacao/cme'
      fullPath: '/operacao/cme'
      preLoaderRoute: typeof AuthenticatedOperacaoCmeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/consultas': {
      id: '/_authenticated/operacao/consultas'
      path: '/operacao/consultas'
      fullPath: '/operacao/consultas'
      preLoaderRoute: typeof AuthenticatedOperacaoConsultasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/procedimentos': {
      id: '/_authenticated/operacao/procedimentos'
      path: '/operacao/procedimentos'
      fullPath: '/operacao/procedimentos'
      preLoaderRoute: typeof AuthenticatedOperacaoProcedimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/prontuarios': {
      id: '/_authenticated/operacao/prontuarios'
      path: '/operacao/prontuarios'
      fullPath: '/operacao/prontuarios'
      preLoaderRoute: typeof AuthenticatedOperacaoProntuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/recuperacao': {
      id: '/_authenticated/operacao/recuperacao'
      path: '/operacao/recuperacao'
      fullPath: '/operacao/recuperacao'
      preLoaderRoute: typeof AuthenticatedOperacaoRecuperacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pacientes/': {
      id: '/_authenticated/pacientes/'
      path: '/pacientes'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof AuthenticatedPacientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pacientes/$pacienteId': {
      id: '/_authenticated/pacientes/$pacienteId'
      path: '/pacientes/$pacienteId'
      fullPath: '/pacientes/$pacienteId'
      preLoaderRoute: typeof AuthenticatedPacientesPacienteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedGestaoCrmRoute: typeof AuthenticatedGestaoCrmRoute
  AuthenticatedGestaoDocumentosRoute: typeof AuthenticatedGestaoDocumentosRoute
  AuthenticatedGestaoEquipeRoute: typeof AuthenticatedGestaoEquipeRoute
  AuthenticatedGestaoEstoqueRoute: typeof AuthenticatedGestaoEstoqueRoute
  AuthenticatedGestaoFinanceiroRoute: typeof AuthenticatedGestaoFinanceiroRoute
  AuthenticatedOperacaoCentroCirurgicoRoute: typeof AuthenticatedOperacaoCentroCirurgicoRoute
  AuthenticatedOperacaoCmeRoute: typeof AuthenticatedOperacaoCmeRoute
  AuthenticatedOperacaoConsultasRoute: typeof AuthenticatedOperacaoConsultasRoute
  AuthenticatedOperacaoProcedimentosRoute: typeof AuthenticatedOperacaoProcedimentosRoute
  AuthenticatedOperacaoProntuariosRoute: typeof AuthenticatedOperacaoProntuariosRoute
  AuthenticatedOperacaoRecuperacaoRoute: typeof AuthenticatedOperacaoRecuperacaoRoute
  AuthenticatedPacientesPacienteIdRoute: typeof AuthenticatedPacientesPacienteIdRoute
  AuthenticatedPacientesIndexRoute: typeof AuthenticatedPacientesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedGestaoCrmRoute: AuthenticatedGestaoCrmRoute,
  AuthenticatedGestaoDocumentosRoute: AuthenticatedGestaoDocumentosRoute,
  AuthenticatedGestaoEquipeRoute: AuthenticatedGestaoEquipeRoute,
  AuthenticatedGestaoEstoqueRoute: AuthenticatedGestaoEstoqueRoute,
  AuthenticatedGestaoFinanceiroRoute: AuthenticatedGestaoFinanceiroRoute,
  AuthenticatedOperacaoCentroCirurgicoRoute:
    AuthenticatedOperacaoCentroCirurgicoRoute,
  AuthenticatedOperacaoCmeRoute: AuthenticatedOperacaoCmeRoute,
  AuthenticatedOperacaoConsultasRoute: AuthenticatedOperacaoConsultasRoute,
  AuthenticatedOperacaoProcedimentosRoute:
    AuthenticatedOperacaoProcedimentosRoute,
  AuthenticatedOperacaoProntuariosRoute: AuthenticatedOperacaoProntuariosRoute,
  AuthenticatedOperacaoRecuperacaoRoute: AuthenticatedOperacaoRecuperacaoRoute,
  AuthenticatedPacientesPacienteIdRoute: AuthenticatedPacientesPacienteIdRoute,
  AuthenticatedPacientesIndexRoute: AuthenticatedPacientesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
