// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  let SUPABASE_URL =
    import.meta.env["VITE_SUPABASE_URL"] ||
    process.env["SUPABASE_URL"] ||
    process.env["VITE_SUPABASE_URL"] ||
    "https://gjkclsptqenataswosjp.supabase.co";

  if (SUPABASE_URL.includes("bgfxqhovkvstducqcsva")) {
    SUPABASE_URL = "https://gjkclsptqenataswosjp.supabase.co";
  }

  let SUPABASE_PUBLISHABLE_KEY =
    import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] ||
    process.env["SUPABASE_PUBLISHABLE_KEY"] ||
    process.env["VITE_SUPABASE_PUBLISHABLE_KEY"] ||
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdqa2Nsc3B0cWVuYXRhc3dvc2pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkwMDA1NTgsImV4cCI6MjEwNDU3NjU1OH0.Yy6RG4v7ypY0Efxq9LjBCW2h0QcQlw0ICBukQrADLJo";

  if (SUPABASE_PUBLISHABLE_KEY.includes("WYddJLdLjHaeh6ZHIxf61Q_OkJdC5Qj")) {
    SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdqa2Nsc3B0cWVuYXRhc3dvc2pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkwMDA1NTgsImV4cCI6MjEwNDU3NjU1OH0.Yy6RG4v7ypY0Efxq9LjBCW2h0QcQlw0ICBukQrADLJo";
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
